language: python

env:
  - TRAMPOLINE_BUILD_FILE=tests/python/run_tests.sh
    TRAMPOLINE_IMAGE=gcr.io/cloud-devrel-kokoro-resources/docker-ci-helper/python
    TRAMPOLINE_DOCKERFILE=docker/python/Dockerfile
    TRAMPOLINE_SERVICE_ACCOUNT=ci/service-account.json
    TEST_ENV=test
    PATH=/tmp/google-cloud-sdk/bin:${PATH}

# This openssl command will fail for PRs from other repo,
# so ignoring failure.
before_install:
  - >
    openssl aes-256-cbc -K $encrypted_22c8f4d50f05_key
    -iv $encrypted_22c8f4d50f05_iv
    -in ci/service-account.json.enc
    -out ci/service-account.json -d | /bin/true
# For `gcloud auth configure docker`
install: ci/install-gcloud.sh
script: ./trampoline_v2.sh
