language: python

env:
  - TRAMPOLINE_BUILD_FILE=tests/python/run_tests.sh
    TRAMPOLINE_IMAGE=gcr.io/cloud-devrel-kokoro-resources/docker-ci-helper/python
    TRAMPOLINE_DOCKERFILE=docker/python/Dockerfile
    TRAMPOLINE_SERVICE_ACCOUNT=ci/service-account.json
    TEST_ENV=test

before_install:
  - >
    openssl aes-256-cbc -K $encrypted_22c8f4d50f05_key
    -iv $encrypted_22c8f4d50f05_iv
    -in service-account.json.enc
    -out ci/service-account.json -d
# For `gcloud auth configure docker`
install: sudo gcloud components install docker-credential-gcr
script: ./trampoline_v2.sh
